!org.hawkular.qe.tools.perfrepo.Settings
perfrepo:
   csvFileDelimiter: \,
parameters:
# SET_PARAMETERS
tags:
# SET_TAGS
metrics:
- !org.hawkular.qe.tools.perfrepo.CSVColMap
  sourceCSVFilePath: ./rt.csv
  metricColRelation:
  - !org.hawkular.qe.tools.perfrepo.MetricColRelation
    CSVColumnName: Maximum
    remoteMetricName: Response time - max
  - !org.hawkular.qe.tools.perfrepo.MetricColRelation
    CSVColumnName: Average
    remoteMetricName: Response time - avg
  - !org.hawkular.qe.tools.perfrepo.MetricColRelation
    CSVColumnName: Minimum
    remoteMetricName: Response time - min
- !org.hawkular.qe.tools.perfrepo.CSVColMap
  sourceCSVFilePath: ./throughput.csv
  metricColRelation:
  - !org.hawkular.qe.tools.perfrepo.MetricColRelation
    CSVColumnName: Average
    remoteMetricName: Throughput - avg
  - !org.hawkular.qe.tools.perfrepo.MetricColRelation
    CSVColumnName: Minimum
    remoteMetricName: Throughput - min
  - !org.hawkular.qe.tools.perfrepo.MetricColRelation
    CSVColumnName: Maximum
    remoteMetricName: Throughput - max
- !org.hawkular.qe.tools.perfrepo.CSVColMap
  sourceCSVFilePath: ./datapoints.csv
  metricColRelation:
  - !org.hawkular.qe.tools.perfrepo.MetricColRelation
    CSVColumnName: Datapoints
    remoteMetricName: Datapoints
attachments:
# SET_ATTACHMENTS
